server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

devtools:
  restart:
    enabled: true
  livereload:
    enabled: true

metadata:
  folder:
    path: src/main/resources/static/assets/metadata