server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mustache:
    servlet:
      cache: false
  datasource:
      jdbc-url: jdbc:mariadb://192.168.0.41:13306/assets?serverTimezone=UTC&characterEncoding=UTF-8
      username: user
      password: userpw
      driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
      dialect: org.hibernate.dialect.MariaDB103Dialect
  jackson:
    serialization:
      fail-on-empty-beans: false

devtools:
  restart:
    enabled: true
  livereload:
    enabled: true

logging:
  level:
    org.hibernate.SQL: debug

metadata:
  folder:
    path: src/main/resources/static/assets/metadata